window.TEAM_DATA = [
  {
    "team": "Stark",
    "batches": [
      {
        "year": "2025",
        "students": [
          "Fariah Naseem - 45",
          "Siddeshwar S - 168",
          "S R Janashree - 61",
          "V Vidhya - 196",
          "Jothika K - 67",
          "Nithin - 121",
          "Sakthi Srei K - 146",
          "Viswaroobini S - 199",
          "M Mithra Malini - 104",
          "Venkatesh M V - 195",
          "Nadar Prakash Saravanan - 115",
          "Hari shankar B - 51",
          "Sriharini - 174",
          "Deepha A.S - 30",
          "Jeya Surya - 64",
          "Aswath - 19",
          "Resika P R - 142",
          "Pranesh T - 129",
          "Nathisha P - 118",
          "Mithrajeeth - 105",
          "Megavarnan - 100",
          "Vinothini V - 198",
          "Praveen Kumar S - 130",
          "KAVYA VHARSHINI R G - 76",
          "Mukesh.M - 112",
          "Marwa Esahak - 98",
          "S Harishmithaa - 53",
          "Sudharshana M K - 180",
          "S.Devi - 35",
          "Dhamodharan A - 36",
          "Sameeha. S - 147",
          "Dharmikaa D - 40",
          "Joyce Mary S - 68",
          "Mohanapriya V - 106",
          "Madhumithra K - 93",
          "Shree vaishak Roshan S K - 164",
          "Chakravarthy.M.A - 27",
          "R.Ramsankar - 140",
          "Devavarsini M S - 34",
          "Mariyam Ayisha - 97",
          "Dharika.S - 39",
          "Shakthiram T - 161",
          "Karthika - 72",
          "J. Keerthisvar - 81",
          "Aarthi.S.A - 2",
          "Keerthana Narayanan - 77",
          "Hemavathy G - 56",
          "Sanjana M - 153",
          "Mirunalini J K - 102",
          "Mohanadarshini Kannan - 107"
        ]
      },
      {
        "year": "2023",
        "students": [
          "Sriram Raghav B",
          "Mithun Kanna AS",
          "Dhinesh K",
          "Anbarasan K",
          "Abinash S",
          "Koushik Sudhan SD",
          "Hirthick S",
          "Mugunthan M",
          "Karthick K",
          "Hariram G",
          "Dina A",
          "Yokesh R",
          "Vimal Adithiya A",
          "Shanmuganathan S",
          "Blesson Paul J",
          "Dashrath Sivakumar",
          "Raghul S",
          "Yazhini C",
          "Praba V",
          "Keerthana ramesh",
          "Kinnes geethai",
          "Sruthe E",
          "Aswiga S",
          "Padmaja B",
          "Pranavi sivakannan",
          "Visalini P T",
          "Yashiha R",
          "Nandhana R",
          "Meena S",
          "Jaiyasri S",
          "Nandhitha R",
          "Sushmi M R",
          "Rithika M",
          "Bharathi A",
          "Harivarshini M"
        ]
      },
      {
        "year": "2024",
        "students": [
          "Arif K",
          "Harish raghul M",
          "Hemnath",
          "Ganesh Aravind",
          "Aswin",
          "Kavin",
          "Jai kiran",
          "Sanjay Ganesh",
          "Harish M",
          "Mohideen",
          "Naveen Kumar M",
          "Shaaru prasana",
          "Sri varshini",
          "Megha V",
          "Sreeka",
          "Sowbarnika selvakumar",
          "Vikashini G",
          "Janani R M",
          "Jayapriya J",
          "Sumiya thasneem",
          "Dharani sriÂ Â K R",
          "Nandhini V",
          "Shivani gopinath",
          "Kamala vardhini",
          "Uma ranjini",
          "Bhagavathy devi",
          "Nabesha M",
          "Jaya Sri V P",
          "Karthiga shree",
          "Virtuouslin",
          "Mahita",
          "Induvadhani",
          "Kaviya",
          "Ashika arulkumar",
          "Ragavi",
          "Sreeja",
          "Sharmina",
          "Madhushree Ramu",
          "Darshana Pk"
        ]
      }
    ]
  },
  {
    "team": "Targaryen",
    "batches": [
      {
        "year": "2025",
        "students": [
          "V.Santhiya - 156",
          "Mullai selvan B S - 113",
          "K.Deepthika - 32",
          "S.Dharshini - 43",
          "Abhijith S - 4",
          "Miruthulha.S.A - 103",
          "Keerthiga K - 80",
          "Kamali. V.V - 70",
          "Keerthi sree M S - 79",
          "Ragha harishni.B - 136",
          "Suba Muthusamy - 178",
          "Tamilselvi C - 186",
          "Srinithi Sivasamy - 176",
          "Monish R - 109",
          "Sibikarthikha K - 167",
          "SuruthiSubramaniyan - 182",
          "Sneha S - 171",
          "Varsheni M - 193",
          "Surya M - 183",
          "Sameetha. P - 148",
          "Bharani.T.K - 23",
          "Gojashree A - 47",
          "Gobika N - 46",
          "Akalya. S - 7",
          "Sivashree R - 170",
          "Samyuktha V S - 150",
          "Preethi M S - 131",
          "Pradheepa S - 127",
          "Sankavi M - 155",
          "Athulya Sabu - 20",
          "Ritika Murugasamy - 145",
          "Shobanasri G - 163",
          "Nithya Sri M - 123",
          "Keerthana S - 78",
          "B. Aishwarya - 6",
          "P.Maxie Milian Jeevarekha - 99",
          "Madhumitha K S - 90",
          "Tamil Tamilarasi - 185",
          "Angel Keren J - 11",
          "E.Yalavarkuzhali - 200",
          "Ragapriya T -134",
          "Sangamithra P - 152",
          "Arivukkarasi K - 15",
          "Monish G - 108",
          "Dharanidharan k - 37",
          "Hari Keshav - 50",
          "P.Sowmiya - 173",
          "Manju Nithin - 95",
          "A Suryakala - 184",
          "Karunya J - 73"
        ]
      },
      {
        "year": "2023",
        "students": [
          "Sree prasanna chenthur A",
          "Vishwa S",
          "Vimal raj A",
          "Nithesh raj M",
          "U Tarun",
          "Balamurugan C",
          "Athish rahavendra R K",
          "Balaji G",
          "Dhanushkaran R",
          "Shrihari swamyappan",
          "Prathyum balaji V",
          "Vedavyas R D",
          "Mohandinesh M",
          "Rakesh R D",
          "Kapilasundar R",
          "Gunasarathi K",
          "Gokulakrishnan R",
          "Karthikeyan P",
          "Harthipriya P",
          "Meganmanjari M",
          "Sindhu S",
          "Nanthini P",
          "Aswini C",
          "Sushmitha B",
          "Suganthi S",
          "Abinaya T",
          "Naveena N",
          "Keshan S",
          "Reena cathlin J",
          "Vidhya shree V T",
          "Swetha S",
          "Jayanthini priya G",
          "Venmathi M",
          "Madhumitha S",
          "Deepika J",
          "Stella sophia A",
          "Sridurga muthusamy",
          "Sujitha I",
          "Shri abirami V S",
          "Jayasree A G",
          "Vismita S",
          "Shrinitha S"
        ]
      },
      {
        "year": "2024",
        "students": [
          "Abinaya",
          "Abirami",
          "Dharshini",
          "Ilamathi",
          "Javini",
          "Jayden",
          "Sarah hibah",
          "Jubil Timothy",
          "Kavinaya Sri",
          "ANBUMANI.R",
          "BHARATHI RAJA M",
          "SANJAI PRANESH.D",
          "RAMPRASATH.M.V",
          "KARTHICKRAJA R",
          "PUSHPARAJ P",
          "NITHINBALA AS",
          "JERRY.J",
          "SRIHARAN.K",
          "RITHIKA",
          "VARSHA SRI.A",
          "SWETHA P",
          "SAMHITA.P",
          "SWATHI B",
          "SOVEMITASHRI S",
          "SINDHU.N",
          "AKSHAYAH A P",
          "SOWBARNIGA SRI",
          "DHANU RAGHAVI.S",
          "VISHNUPRIYA A R",
          "SIVASUNDARI D",
          "Deva dharshini"
        ]
      }
    ]
  },
  {
    "team": "Lannister",
    "batches": [
      {
        "year": "2025",
        "students": [
          "Kanika sree RG - 71",
          "Kiruthik.K - 82",
          "Jai Shruthi - 60",
          "B.Nareshmaa - 117",
          "Vasundhra J P - 194",
          "Rithivika S. M. R - 143",
          "Dharaniya V - 38",
          "Nakshatra N D - 116",
          "Buvaneshwar VG - 26",
          "Vaishnavi - 189",
          "S.Aniritha - 12",
          "Harithra S R - 54",
          "Birundhadevi S - 25",
          "Asmitha.S - 18",
          "Jityaa NN - 65",
          "S .Lithika - 85",
          "Manis Ram.K - 94",
          "Kaveya Elangukumaran07 - 74",
          "Rithuvaruna G - 144",
          "Aayishah Naureen M - 3",
          "TA Thanush Karthik - 187",
          "Nithyasri Lakshmi.g.k - 124",
          "Monisha P - 110",
          "JOSHEGA S - 66",
          "Sandhiga sri - 151",
          "Sarrayu S - 157",
          "Madhan S - 88",
          "Ardra.V.R - 14",
          "K.Madhumitha - 89",
          "Akhilan A - 8",
          "M.Preethika - 132",
          "Reshmmi mohan - 141",
          "Vino Gnanamoorthy - 197",
          "Deepak S - 29",
          "Shwetha Dharmalingam - 166",
          "Shrivalli TS - 165",
          "Aarthi A - 1",
          "Selva Kumar - 160",
          "Srinithisha .S - 177",
          "Suman K S - 181",
          "Sarvesh.R - 159",
          "Ariya - 16",
          "Kalaiyarasu. B - 69",
          "Maanushri K - 87",
          "Nikshithaa shrri J S - 120",
          "Ashika R - 17",
          "Varsha Shree.C - 192",
          "Gugun - 49",
          "Shiblin Fiona A M - 162",
          "Madhumitha Shanmugasundaram - 92"
        ]
      },
      {
        "year": "2023",
        "students": [
          "THIVYA PRASATH S AMUTHAN K",
          "RISHIKANTH N",
          "NAVIN PRANAV P A",
          "RISHIKESH S C",
          "GOKUL KRISHNAN P",
          "ASAF ALI MUHAIYADEEN O",
          "KOUSHIK DS",
          "LIVIN NOVA R",
          "VIKAS D",
          "VIGNESHWAR N R",
          "NARAYANAN V",
          "SARANYA",
          "MANUSHRI",
          "SONA",
          "SRUTHIKA",
          "LAVANYA SRI",
          "LAKSHANYA",
          "RIDDHI",
          "KIRUTHIGA A G",
          "SWATHIGA",
          "SRINIDHI",
          "HAREETI",
          "RITHANIYA",
          "KAVIYA",
          "CHARUNETHRA",
          "DIVYA S R",
          "NANDHINI S",
          "DIVYA SRI",
          "ANANYA A G",
          "DHARANIKA",
          "SELVATHIRUMAGAL",
          "SHREYA",
          "PARAMESHWARI",
          "RAFIYA",
          "NISHITHA",
          "VARSHA"
        ]
      },
      {
        "year": "2024",
        "students": [
          "MUKESH",
          "AAKASH",
          "MOHAMMED IBRAHIM",
          "AJAY ROHITH",
          "VASANTH",
          "WILCHRIST",
          "KARANDEV",
          "NIRANJAN DP",
          "RAJAY",
          "SABARISH",
          "NIRMAL RAJ",
          "DHARUN RAJ",
          "ARUN",
          "NIRANJAN B",
          "SANJAY R",
          "NIRMAL RAJ",
          "MANIKANDAN",
          "HEMANTH BALA",
          "GUNA NIKITHA",
          "AMOGA",
          "AKSHAYA P K",
          "APARNA P DIPIN",
          "DHANYASRI R S",
          "JEMILA",
          "KEERTHI SREE",
          "MAHASREE",
          "NISHANTHINI",
          "SHEEBA",
          "TAMILARASI",
          "TANUSHRI",
          "TEJASHA",
          "THANVANTHI",
          "VISMITA",
          "ANN LYDIA LEO",
          "AAMINA",
          "KARTHIGA",
          "KAVIYAPRIYA",
          "POOJABHARATHI",
          "THEVADHARSHINI"
        ]
      }
    ]
  },
  {
    "team": "Baratheon",
    "batches": [
      {
        "year": "2025",
        "students": [
          "Premanandhi S - 133",
          "Varsha K - 191",
          "Krishnabalan - 83",
          "Deepitha N - 31",
          "Lokesh M - 86",
          "P. Barath - 21",
          "Perarasu V - 126",
          "Hema Varshini panchavarnam M - 55",
          "Ragavi P - 135",
          "Annie Ruby - 13",
          "Harini A - 52",
          "Uma Selvi P - 188",
          "Indaresh - 58",
          "Honey sri - 57",
          "Aditya Venkatachalam - 5",
          "PRANAV R - 128",
          "T.Siva Priya - 169",
          "Mynavathi P - 114",
          "Nikhil Makhija R - 119",
          "BarathGokul SK - 22",
          "Nithish - 122",
          "Vaishnavi S - 190",
          "Diksha S - 44",
          "Padmesh M.S. - 125",
          "Rajesh kannan - 138",
          "Mirni L - 101",
          "P.S.Krisika - 84",
          "Delishaa khaaleeq - 33",
          "Srikavi K - 175",
          "Raghunanthan.S - 137",
          "Jason Rufus - 62",
          "Jayabanu V - 63",
          "R.Madhumitha - 91",
          "Aksaya Yazhini - 9",
          "Sarveis S - 158",
          "Mousika gopi - 111",
          "Marish M - 96",
          "Soundhari S - 172",
          "Sanjay S - 154",
          "R. Kaviko Nijin - 75",
          "Iyyanar S - 59",
          "BharaniDharan.M - 24",
          "Daksini B M - 28",
          "V Gowtham - 48",
          "Dharshini Priya C - 42",
          "Subiksha V S - 179",
          "Dharshanraju J - 41",
          "Akshaya - 10",
          "Ram Laxmi A R - 139",
          "Samiksha GR - 149"
        ]
      },
      {
        "year": "2023",
        "students": [
          "ENIYAVANãƒ»P",
          "NILAVAN. LR",
          "THARUN. J.L.",
          "SANJAI.S",
          "SATHISHKUMAR.T.",
          "RITHICK RANTAN â€¢H.",
          "PRABAV S",
          "DHEEKSHITH .G",
          "AKILESWAR LOKESH",
          "PUGAZH SELVAN. S",
          "NANDHA KISHORE D.V.",
          "AAKASHâ€¢ M.Câ€¢",
          "AJAYMADHAN. T.",
          "VISHAL- GT.",
          "JENITO DANI",
          "MITHRA. D.",
          "BHUVANA.S. V.",
          "BOOMIKAâ€¢ Pâ€¢",
          "RATHY.N.R.",
          "AZHAGU RAKSHIKAAâ€¢ N.K.",
          "REVATHI â€¢A.",
          "ANUVARSHINI â€¢ B'S",
          "NIKITHA.Gâ€¢A.",
          "KARUNYAâ€¢ J.",
          "FAHEEMAâ€¢M.",
          "VAISHALI â€¢ E.",
          "PAVITHRAâ€¢ M.",
          "JUSHVINI R.",
          "AYSHAAFRINâ€¢U",
          "SREEMATHI.S",
          "SWATHI PRIVADHARSHINI.N",
          "NITHTHILAM.A.",
          "KANISHKA",
          "NIRMALA"
        ]
      },
      {
        "year": "2024",
        "students": [
          "Naveen kumar N",
          "Arvinth P",
          "Sivanesan K",
          "Kiran Raj",
          "Vidyacharan",
          "Dharunesh",
          "Kadalvendhan",
          "Kannan",
          "Vishnubharathiram",
          "Gnaneshwaran A C",
          "Santhosh",
          "Ajith",
          "Prakash raj",
          "Boomika",
          "Suwetha A",
          "Jayasri S",
          "Gayathri N",
          "Athira K S",
          "Abarna H",
          "Muthukeerthika",
          "Vijayapriya",
          "Swathi sree karthikeyan",
          "Adheira A S",
          "Lalitha",
          "Priyanka B",
          "Malini P",
          "Dhanuvarshini J",
          "Poojasri S",
          "Yogasree S",
          "Bhavyasri N",
          "Monashri J P",
          "Madhubala K",
          "Sharmila S",
          "Arsija seen",
          "Dhanyaa sri S",
          "Rishvanthi S",
          "Hamsalaya M S"
        ]
      }
    ]
  }
];

